name: example
description: "Example to showcase use cases of Better Player."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  better_player:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.10
  visibility_detector: ^0.3.3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true